name: Build and Push Docker Image

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest
    environment: python-project

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Harbor Registry
      - name: Log in to Harbor registry
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
          HARBOR_URL: ${{ secrets.HARBOR_URL }}
        run: |
          echo "${HARBOR_PASSWORD}" | docker login "${HARBOR_URL}" --username "${HARBOR_USERNAME}" --password-stdin

      # Debug Docker Tag (Temporary Step)
      - name: Debug Docker Tag
        run: echo "Docker Tag: ${{ secrets.HARBOR_URL }}/flask_cicd/hello-flask:latest"

      # Build the Docker Image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.HARBOR_URL }}/flask_cicd/hello-flask:latest .

      # Push the Docker Image
      - name: Push the Docker image
        run: docker push ${{ secrets.HARBOR_URL }}/flask_cicd/hello-flask:latest
