name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: python-project

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Harbor credentials and URL using GITHUB_ENV
      - name: Set Harbor Environment Variables
        run: |
          echo "HARBOR_USERNAME=${{ secrets.HARBOR_USERNAME }}" >> $GITHUB_ENV
          echo "HARBOR_PASSWORD=${{ secrets.HARBOR_PASSWORD }}" >> $GITHUB_ENV
          echo "HARBOR_URL=${{ secrets.HARBOR_URL }}" >> $GITHUB_ENV

      # Log in to Harbor Registry
      - name: Log in to Harbor registry
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login "${{ vars.HARBOR_URL }}" --username "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      # Debug Docker Tag
      - name: Debug Docker Tag
        run: |
          DOCKER_TAG="${{ vars.HARBOR_PASSWORD }}/flask_cicd/hello-flask:latest"
          echo "Docker Tag: $DOCKER_TAG"

      # Debug Harbor URL
      - name: Debug Harbor URL
        run: |
          echo "HARBOR_URL: $HARBOR_URL"
          echo "Docker Tag: ${{ vars.HARBOR_PASSWORD }}/flask_cicd/hello-flask:latest"

      # Build the Docker Image
      - name: Build the Docker image
        run: docker build -t ${{ vars.HARBOR_PASSWORD }}/flask_cicd/hello-flask:latest .

      # Push the Docker Image
      - name: Push the Docker image
        run: docker push ${{ vars.HARBOR_PASSWORD }}/flask_cicd/hello-flask:latest
