name: Build and Push Docker Image

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest
    environment: python-project  # Specify the environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Harbor registry
      - name: Log in to Harbor registry
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
          HARBOR_URL: ${{ secrets.HARBOR_URL }}
        run: |
          echo "${HARBOR_PASSWORD}" | docker login "${HARBOR_URL}" --username "${HARBOR_USERNAME}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.HARBOR_URL }}/flask_cicd/hello-flask:latest .

      # Step 4: Push the Docker image to Harbor
      - name: Push the Docker image
        run: docker push ${{ secrets.HARBOR_URL }}/flask_cicd/hello-flask:latest
